### ISSUE TITLE
[Update] Exit survey 2 page - add an option for "no course"

### ISSUE THREAD

**Issue by subwaymatch** [mendoza-research/cgmv-survey#6]
> On the exit survey 2 page, question "How many undergraduate or graduate accounting and finance courses have you taken..."? can we add an option below the accounting and finance options that says "I have not taken any accounting or finance courses." and then give students and error if they do not select any of these options? 

> Yes. I will work on this update. Thank you!

**Comment by subwaymatch** [comment]
@kimendoz Do we need a new field to indicate whether a participant has selected the "I have not taken any accounting or finance courses." option? That will be redundant since having no values in both `num_accy_courses` and `num_fin_courses` would indicate that the participant has selected the "have not taken" option, but we can certainly create a new field for it if that's more convenient. 🤡

**Comment by kimendoz** [comment]
Hi Park,

We want them to actively select something for the question. This way if someone with accy/finance experience accidentally leaves the fields blank we don’t mistakenly say they have zero experience.

Thank you!
Kim


On May 24, 2021, at 2:52 AM, Ye Joo Park ***@***.***> wrote:

﻿

@kimendoz<https://urldefense.com/v3/__https://github.com/kimendoz__;!!DZ3fjg!vYkwhmUcLpcjM4_Ky_G6gXdrJXCTtG7xLT-d0VAu0bSx0xCRPDzgeHAzW-0aLXtXpzU$> Do we need a new field to indicate whether a participant has selected the "I have not taken any accounting or finance courses." option? That will be redundant since having no values in both num_accy_courses and num_fin_courses would indicate that the participant has selected the "have not taken" option, but we can certainly create a new field for it if that's more convenient. 🤡

**Comment by subwaymatch** [comment]
@kimendoz Sorry. I meant a new column in the database. Do we need to record whether a user has selected the "have not taken" option to a new column? 

![image](https://user-images.githubusercontent.com/1064036/119376954-6662a800-bc71-11eb-9f73-fea2bd40744c.png)

**Comment by kimendoz** [comment]
Oh yes! That would be helpful!

Thank you!

Kim

On May 24, 2021, at 11:25 AM, Ye Joo Park ***@***.***> wrote:

﻿

@kimendoz<https://urldefense.com/v3/__https://github.com/kimendoz__;!!DZ3fjg!taNk4hpLrjmQjM5N2I8OgVkgYjg-4dI-bAzOS7UYxq1zpgVtstKcXw7RCvbjv3epK1s$> Sorry. I meant a new column in the database. Do we need to record whether a user has selected the "have not taken" option to a new column?

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/1064036/119376954-6662a800-bc71-11eb-9f73-fea2bd40744c.png__;!!DZ3fjg!taNk4hpLrjmQjM5N2I8OgVkgYjg-4dI-bAzOS7UYxq1zpgVtstKcXw7RCvbjWPT_cwk$>

**Comment by subwaymatch** [comment]
Resolved via 08dad0c8028f5e1174e7eb32c2023207f4e8f7b3
